"""Add name, phone, and application_date fields to User model

Revision ID: 50cd63d6c6db
Revises: 
Create Date: 2025-05-25 14:37:33.203991

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '50cd63d6c6db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))

    # Update existing rows with default values
    op.execute("UPDATE user SET name = username WHERE name IS NULL")
    op.execute("UPDATE user SET application_date = CURRENT_TIMESTAMP WHERE application_date IS NULL")

    # Now make the columns NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('application_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
